"""
Codex App-Server Protocol — Generated Constants

AUTO-GENERATED from codex_app_server_protocol.schemas.json
Do not edit by hand. Re-run scripts/codex_schema_extract.py to regenerate.
"""

# All known event types from EventMsg union
EVENT_TYPES = frozenset({
    "agent_message",
    "agent_message_content_delta",
    "agent_message_delta",
    "agent_reasoning",
    "agent_reasoning_delta",
    "agent_reasoning_raw_content",
    "agent_reasoning_raw_content_delta",
    "agent_reasoning_section_break",
    "apply_patch_approval_request",
    "background_event",
    "collab_agent_interaction_begin",
    "collab_agent_interaction_end",
    "collab_agent_spawn_begin",
    "collab_agent_spawn_end",
    "collab_close_begin",
    "collab_close_end",
    "collab_resume_begin",
    "collab_resume_end",
    "collab_waiting_begin",
    "collab_waiting_end",
    "context_compacted",
    "deprecation_notice",
    "dynamic_tool_call_request",
    "elicitation_request",
    "entered_review_mode",
    "error",
    "exec_approval_request",
    "exec_command_begin",
    "exec_command_end",
    "exec_command_output_delta",
    "exited_review_mode",
    "get_history_entry_response",
    "item_completed",
    "item_started",
    "list_custom_prompts_response",
    "list_remote_skills_response",
    "list_skills_response",
    "mcp_list_tools_response",
    "mcp_startup_complete",
    "mcp_startup_update",
    "mcp_tool_call_begin",
    "mcp_tool_call_end",
    "model_reroute",
    "patch_apply_begin",
    "patch_apply_end",
    "plan_delta",
    "plan_update",
    "raw_response_item",
    "reasoning_content_delta",
    "reasoning_raw_content_delta",
    "remote_skill_downloaded",
    "request_user_input",
    "session_configured",
    "shutdown_complete",
    "skills_update_available",
    "stream_error",
    "task_complete",
    "task_started",
    "terminal_interaction",
    "thread_name_updated",
    "thread_rolled_back",
    "token_count",
    "turn_aborted",
    "turn_diff",
    "undo_completed",
    "undo_started",
    "user_message",
    "view_image_tool_call",
    "warning",
    "web_search_begin",
    "web_search_end",
})

# Collab (subagent) event types
COLLAB_EVENT_TYPES = frozenset({
    "collab_agent_interaction_begin",
    "collab_agent_interaction_end",
    "collab_agent_spawn_begin",
    "collab_agent_spawn_end",
    "collab_close_begin",
    "collab_close_end",
    "collab_resume_begin",
    "collab_resume_end",
    "collab_waiting_begin",
    "collab_waiting_end",
})

# Field names per event type (excluding "type" discriminator)
EVENT_FIELDS = {
    "agent_message": ['message'],
    "agent_message_content_delta": ['delta', 'item_id', 'thread_id', 'turn_id'],
    "agent_message_delta": ['delta'],
    "agent_reasoning": ['text'],
    "agent_reasoning_delta": ['delta'],
    "agent_reasoning_raw_content": ['text'],
    "agent_reasoning_raw_content_delta": ['delta'],
    "agent_reasoning_section_break": ['item_id', 'summary_index'],
    "apply_patch_approval_request": ['call_id', 'changes', 'grant_root', 'reason', 'turn_id'],
    "background_event": ['message'],
    "collab_agent_interaction_begin": ['call_id', 'prompt', 'receiver_thread_id', 'sender_thread_id'],
    "collab_agent_interaction_end": ['call_id', 'prompt', 'receiver_thread_id', 'sender_thread_id', 'status'],
    "collab_agent_spawn_begin": ['call_id', 'prompt', 'sender_thread_id'],
    "collab_agent_spawn_end": ['call_id', 'new_thread_id', 'prompt', 'sender_thread_id', 'status'],
    "collab_close_begin": ['call_id', 'receiver_thread_id', 'sender_thread_id'],
    "collab_close_end": ['call_id', 'receiver_thread_id', 'sender_thread_id', 'status'],
    "collab_resume_begin": ['call_id', 'receiver_thread_id', 'sender_thread_id'],
    "collab_resume_end": ['call_id', 'receiver_thread_id', 'sender_thread_id', 'status'],
    "collab_waiting_begin": ['call_id', 'receiver_thread_ids', 'sender_thread_id'],
    "collab_waiting_end": ['call_id', 'sender_thread_id', 'statuses'],
    "deprecation_notice": ['details', 'summary'],
    "dynamic_tool_call_request": ['arguments', 'callId', 'tool', 'turnId'],
    "elicitation_request": ['id', 'message', 'server_name'],
    "entered_review_mode": ['target', 'user_facing_hint'],
    "error": ['codex_error_info', 'message'],
    "exec_approval_request": ['approval_id', 'call_id', 'command', 'cwd', 'network_approval_context', 'parsed_cmd', 'proposed_execpolicy_amendment', 'reason', 'turn_id'],
    "exec_command_begin": ['call_id', 'command', 'cwd', 'interaction_input', 'parsed_cmd', 'process_id', 'source', 'turn_id'],
    "exec_command_end": ['aggregated_output', 'call_id', 'command', 'cwd', 'duration', 'exit_code', 'formatted_output', 'interaction_input', 'parsed_cmd', 'process_id', 'source', 'status', 'stderr', 'stdout', 'turn_id'],
    "exec_command_output_delta": ['call_id', 'chunk', 'stream'],
    "exited_review_mode": ['review_output'],
    "get_history_entry_response": ['entry', 'log_id', 'offset'],
    "item_completed": ['item', 'thread_id', 'turn_id'],
    "item_started": ['item', 'thread_id', 'turn_id'],
    "list_custom_prompts_response": ['custom_prompts'],
    "list_remote_skills_response": ['skills'],
    "list_skills_response": ['skills'],
    "mcp_list_tools_response": ['auth_statuses', 'resource_templates', 'resources', 'tools'],
    "mcp_startup_complete": ['cancelled', 'failed', 'ready'],
    "mcp_startup_update": ['server', 'status'],
    "mcp_tool_call_begin": ['call_id', 'invocation'],
    "mcp_tool_call_end": ['call_id', 'duration', 'invocation', 'result'],
    "model_reroute": ['from_model', 'reason', 'to_model'],
    "patch_apply_begin": ['auto_approved', 'call_id', 'changes', 'turn_id'],
    "patch_apply_end": ['call_id', 'changes', 'status', 'stderr', 'stdout', 'success', 'turn_id'],
    "plan_delta": ['delta', 'item_id', 'thread_id', 'turn_id'],
    "plan_update": ['explanation', 'plan'],
    "raw_response_item": ['item'],
    "reasoning_content_delta": ['delta', 'item_id', 'summary_index', 'thread_id', 'turn_id'],
    "reasoning_raw_content_delta": ['content_index', 'delta', 'item_id', 'thread_id', 'turn_id'],
    "remote_skill_downloaded": ['id', 'name', 'path'],
    "request_user_input": ['call_id', 'questions', 'turn_id'],
    "session_configured": ['approval_policy', 'cwd', 'forked_from_id', 'history_entry_count', 'history_log_id', 'initial_messages', 'model', 'model_provider_id', 'network_proxy', 'reasoning_effort', 'rollout_path', 'sandbox_policy', 'session_id', 'thread_name'],
    "stream_error": ['additional_details', 'codex_error_info', 'message'],
    "task_complete": ['last_agent_message', 'turn_id'],
    "task_started": ['collaboration_mode_kind', 'model_context_window', 'turn_id'],
    "terminal_interaction": ['call_id', 'process_id', 'stdin'],
    "thread_name_updated": ['thread_id', 'thread_name'],
    "thread_rolled_back": ['num_turns'],
    "token_count": ['info', 'rate_limits'],
    "turn_aborted": ['reason', 'turn_id'],
    "turn_diff": ['unified_diff'],
    "undo_completed": ['message', 'success'],
    "undo_started": ['message'],
    "user_message": ['images', 'local_images', 'message', 'text_elements'],
    "view_image_tool_call": ['call_id', 'path'],
    "warning": ['message'],
    "web_search_begin": ['call_id'],
    "web_search_end": ['action', 'call_id', 'query'],
}

# All known RPC method names
RPC_METHODS = frozenset({
    "account/chatgptAuthTokens/refresh",
    "account/login/cancel",
    "account/login/completed",
    "account/login/start",
    "account/logout",
    "account/rateLimits/read",
    "account/rateLimits/updated",
    "account/read",
    "account/updated",
    "addConversationListener",
    "app/list",
    "app/list/updated",
    "applyPatchApproval",
    "archiveConversation",
    "authStatusChange",
    "cancelLoginChatGpt",
    "command/exec",
    "config/batchWrite",
    "config/mcpServer/reload",
    "config/read",
    "config/value/write",
    "configRequirements/read",
    "configWarning",
    "deprecationNotice",
    "error",
    "execCommandApproval",
    "execOneOffCommand",
    "experimentalFeature/list",
    "feedback/upload",
    "forkConversation",
    "fuzzyFileSearch",
    "fuzzyFileSearch/sessionCompleted",
    "fuzzyFileSearch/sessionUpdated",
    "getAuthStatus",
    "getConversationSummary",
    "getUserAgent",
    "getUserSavedConfig",
    "gitDiffToRemote",
    "initialize",
    "initialized",
    "interruptConversation",
    "item/agentMessage/delta",
    "item/commandExecution/outputDelta",
    "item/commandExecution/requestApproval",
    "item/commandExecution/terminalInteraction",
    "item/completed",
    "item/fileChange/outputDelta",
    "item/fileChange/requestApproval",
    "item/mcpToolCall/progress",
    "item/plan/delta",
    "item/reasoning/summaryPartAdded",
    "item/reasoning/summaryTextDelta",
    "item/reasoning/textDelta",
    "item/started",
    "item/tool/call",
    "item/tool/requestUserInput",
    "listConversations",
    "loginApiKey",
    "loginChatGpt",
    "loginChatGptComplete",
    "logoutChatGpt",
    "mcpServer/oauth/login",
    "mcpServer/oauthLogin/completed",
    "mcpServerStatus/list",
    "model/list",
    "model/rerouted",
    "newConversation",
    "rawResponseItem/completed",
    "removeConversationListener",
    "resumeConversation",
    "review/start",
    "sendUserMessage",
    "sendUserTurn",
    "sessionConfigured",
    "setDefaultModel",
    "skills/config/write",
    "skills/list",
    "skills/remote/export",
    "skills/remote/list",
    "thread/archive",
    "thread/archived",
    "thread/compact/start",
    "thread/compacted",
    "thread/fork",
    "thread/list",
    "thread/loaded/list",
    "thread/name/set",
    "thread/name/updated",
    "thread/read",
    "thread/resume",
    "thread/rollback",
    "thread/start",
    "thread/started",
    "thread/tokenUsage/updated",
    "thread/unarchive",
    "thread/unarchived",
    "turn/completed",
    "turn/diff/updated",
    "turn/interrupt",
    "turn/plan/updated",
    "turn/start",
    "turn/started",
    "turn/steer",
    "userInfo",
    "windows/worldWritableWarning",
})

# RPC method -> params $ref (for schema resolution)
RPC_PARAMS_REF = {
    "account/chatgptAuthTokens/refresh": "#/definitions/ChatgptAuthTokensRefreshParams",
    "account/login/cancel": "#/definitions/v2/CancelLoginAccountParams",
    "account/login/completed": "#/definitions/v2/AccountLoginCompletedNotification",
    "account/login/start": "#/definitions/v2/LoginAccountParams",
    "account/logout": None,
    "account/rateLimits/read": None,
    "account/rateLimits/updated": "#/definitions/v2/AccountRateLimitsUpdatedNotification",
    "account/read": "#/definitions/v2/GetAccountParams",
    "account/updated": "#/definitions/v2/AccountUpdatedNotification",
    "addConversationListener": "#/definitions/AddConversationListenerParams",
    "app/list": "#/definitions/v2/AppsListParams",
    "app/list/updated": "#/definitions/v2/AppListUpdatedNotification",
    "applyPatchApproval": "#/definitions/ApplyPatchApprovalParams",
    "archiveConversation": "#/definitions/ArchiveConversationParams",
    "authStatusChange": "#/definitions/AuthStatusChangeNotification",
    "cancelLoginChatGpt": "#/definitions/CancelLoginChatGptParams",
    "command/exec": "#/definitions/v2/CommandExecParams",
    "config/batchWrite": "#/definitions/v2/ConfigBatchWriteParams",
    "config/mcpServer/reload": None,
    "config/read": "#/definitions/v2/ConfigReadParams",
    "config/value/write": "#/definitions/v2/ConfigValueWriteParams",
    "configRequirements/read": None,
    "configWarning": "#/definitions/v2/ConfigWarningNotification",
    "deprecationNotice": "#/definitions/v2/DeprecationNoticeNotification",
    "error": "#/definitions/v2/ErrorNotification",
    "execCommandApproval": "#/definitions/ExecCommandApprovalParams",
    "execOneOffCommand": "#/definitions/ExecOneOffCommandParams",
    "experimentalFeature/list": "#/definitions/v2/ExperimentalFeatureListParams",
    "feedback/upload": "#/definitions/v2/FeedbackUploadParams",
    "forkConversation": "#/definitions/ForkConversationParams",
    "fuzzyFileSearch": "#/definitions/FuzzyFileSearchParams",
    "fuzzyFileSearch/sessionCompleted": "#/definitions/FuzzyFileSearchSessionCompletedNotification",
    "fuzzyFileSearch/sessionUpdated": "#/definitions/FuzzyFileSearchSessionUpdatedNotification",
    "getAuthStatus": "#/definitions/GetAuthStatusParams",
    "getConversationSummary": "#/definitions/GetConversationSummaryParams",
    "getUserAgent": None,
    "getUserSavedConfig": None,
    "gitDiffToRemote": "#/definitions/GitDiffToRemoteParams",
    "initialize": "#/definitions/InitializeParams",
    "initialized": None,
    "interruptConversation": "#/definitions/InterruptConversationParams",
    "item/agentMessage/delta": "#/definitions/v2/AgentMessageDeltaNotification",
    "item/commandExecution/outputDelta": "#/definitions/v2/CommandExecutionOutputDeltaNotification",
    "item/commandExecution/requestApproval": "#/definitions/CommandExecutionRequestApprovalParams",
    "item/commandExecution/terminalInteraction": "#/definitions/v2/TerminalInteractionNotification",
    "item/completed": "#/definitions/v2/ItemCompletedNotification",
    "item/fileChange/outputDelta": "#/definitions/v2/FileChangeOutputDeltaNotification",
    "item/fileChange/requestApproval": "#/definitions/FileChangeRequestApprovalParams",
    "item/mcpToolCall/progress": "#/definitions/v2/McpToolCallProgressNotification",
    "item/plan/delta": "#/definitions/v2/PlanDeltaNotification",
    "item/reasoning/summaryPartAdded": "#/definitions/v2/ReasoningSummaryPartAddedNotification",
    "item/reasoning/summaryTextDelta": "#/definitions/v2/ReasoningSummaryTextDeltaNotification",
    "item/reasoning/textDelta": "#/definitions/v2/ReasoningTextDeltaNotification",
    "item/started": "#/definitions/v2/ItemStartedNotification",
    "item/tool/call": "#/definitions/DynamicToolCallParams",
    "item/tool/requestUserInput": "#/definitions/ToolRequestUserInputParams",
    "listConversations": "#/definitions/ListConversationsParams",
    "loginApiKey": "#/definitions/LoginApiKeyParams",
    "loginChatGpt": None,
    "loginChatGptComplete": "#/definitions/LoginChatGptCompleteNotification",
    "logoutChatGpt": None,
    "mcpServer/oauth/login": "#/definitions/v2/McpServerOauthLoginParams",
    "mcpServer/oauthLogin/completed": "#/definitions/v2/McpServerOauthLoginCompletedNotification",
    "mcpServerStatus/list": "#/definitions/v2/ListMcpServerStatusParams",
    "model/list": "#/definitions/v2/ModelListParams",
    "model/rerouted": "#/definitions/v2/ModelReroutedNotification",
    "newConversation": "#/definitions/NewConversationParams",
    "rawResponseItem/completed": "#/definitions/v2/RawResponseItemCompletedNotification",
    "removeConversationListener": "#/definitions/RemoveConversationListenerParams",
    "resumeConversation": "#/definitions/ResumeConversationParams",
    "review/start": "#/definitions/v2/ReviewStartParams",
    "sendUserMessage": "#/definitions/SendUserMessageParams",
    "sendUserTurn": "#/definitions/SendUserTurnParams",
    "sessionConfigured": "#/definitions/SessionConfiguredNotification",
    "setDefaultModel": "#/definitions/SetDefaultModelParams",
    "skills/config/write": "#/definitions/v2/SkillsConfigWriteParams",
    "skills/list": "#/definitions/v2/SkillsListParams",
    "skills/remote/export": "#/definitions/v2/SkillsRemoteWriteParams",
    "skills/remote/list": "#/definitions/v2/SkillsRemoteReadParams",
    "thread/archive": "#/definitions/v2/ThreadArchiveParams",
    "thread/archived": "#/definitions/v2/ThreadArchivedNotification",
    "thread/compact/start": "#/definitions/v2/ThreadCompactStartParams",
    "thread/compacted": "#/definitions/v2/ContextCompactedNotification",
    "thread/fork": "#/definitions/v2/ThreadForkParams",
    "thread/list": "#/definitions/v2/ThreadListParams",
    "thread/loaded/list": "#/definitions/v2/ThreadLoadedListParams",
    "thread/name/set": "#/definitions/v2/ThreadSetNameParams",
    "thread/name/updated": "#/definitions/v2/ThreadNameUpdatedNotification",
    "thread/read": "#/definitions/v2/ThreadReadParams",
    "thread/resume": "#/definitions/v2/ThreadResumeParams",
    "thread/rollback": "#/definitions/v2/ThreadRollbackParams",
    "thread/start": "#/definitions/v2/ThreadStartParams",
    "thread/started": "#/definitions/v2/ThreadStartedNotification",
    "thread/tokenUsage/updated": "#/definitions/v2/ThreadTokenUsageUpdatedNotification",
    "thread/unarchive": "#/definitions/v2/ThreadUnarchiveParams",
    "thread/unarchived": "#/definitions/v2/ThreadUnarchivedNotification",
    "turn/completed": "#/definitions/v2/TurnCompletedNotification",
    "turn/diff/updated": "#/definitions/v2/TurnDiffUpdatedNotification",
    "turn/interrupt": "#/definitions/v2/TurnInterruptParams",
    "turn/plan/updated": "#/definitions/v2/TurnPlanUpdatedNotification",
    "turn/start": "#/definitions/v2/TurnStartParams",
    "turn/started": "#/definitions/v2/TurnStartedNotification",
    "turn/steer": "#/definitions/v2/TurnSteerParams",
    "userInfo": None,
    "windows/worldWritableWarning": "#/definitions/v2/WindowsWorldWritableWarningNotification",
}
