import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import esbuild from 'esbuild';

const isWatch = process.argv.includes('--watch');
const staticDir = 'rust/crates/als-server/src/static';
const distDir = join(staticDir, 'dist');
const vendorDir = join(staticDir, 'vendor');

mkdirSync(distDir, { recursive: true });

const common = {
  bundle: true,
  sourcemap: true,
  minify: !isWatch,
  logLevel: 'info',
  external: ['https://*'],
  alias: {
    'streaming-markdown': './node_modules/streaming-markdown/smd.min.js',
  },
  loader: {
    '.css': 'text',
  },
  supported: {
    'template-literal': false,
  },
};

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(dirname(dest));
  cpSync(src, dest);
}

function resetManagedVendorAssets() {
  const managedPaths = [
    join(vendorDir, 'fonts', 'jetbrains-mono'),
    join(vendorDir, 'fonts', 'jetbrains-mono.css'),
    join(vendorDir, 'highlight.js'),
    join(vendorDir, 'markdown-it'),
    join(vendorDir, 'socket.io-msgpack-parser'),
    join(vendorDir, 'streaming-markdown'),
    join(vendorDir, 'tribute.css'),
    join(vendorDir, 'tribute.min.js'),
    join(vendorDir, 'xterm'),
  ];
  for (const path of managedPaths) {
    rmSync(path, { recursive: true, force: true });
  }
}

function buildJetBrainsMonoCss() {
  const fontCssFiles = [
    '400.css',
    '400-italic.css',
    '500.css',
    '500-italic.css',
    '600.css',
    '600-italic.css',
    '700.css',
    '700-italic.css',
  ];
  const fontSourceRoot = 'node_modules/@fontsource/jetbrains-mono';
  const fontDestDir = join(vendorDir, 'fonts', 'jetbrains-mono');
  const fontFiles = new Set();
  const rewrittenBlocks = [];

  for (const cssFile of fontCssFiles) {
    const sourcePath = join(fontSourceRoot, cssFile);
    const sourceCss = readFileSync(sourcePath, 'utf8');
    for (const match of sourceCss.matchAll(/url\(\.\/files\/([^)]+?\.woff2)\)/g)) {
      fontFiles.add(match[1]);
    }
    const rewrittenCss = sourceCss.replace(
      /src:\s*url\(\.\/files\/([^)]+?\.woff2)\) format\('woff2'\),\s*url\(\.\/files\/[^)]+?\.woff\) format\('woff'\);/g,
      "src: url('./jetbrains-mono/$1') format('woff2');",
    );
    rewrittenBlocks.push(rewrittenCss.trim());
  }

  ensureDir(fontDestDir);
  for (const fontFile of fontFiles) {
    copyFile(join(fontSourceRoot, 'files', fontFile), join(fontDestDir, fontFile));
  }

  writeFileSync(
    join(vendorDir, 'fonts', 'jetbrains-mono.css'),
    `/* Generated by build.mjs from @fontsource/jetbrains-mono */\n\n${rewrittenBlocks.join('\n\n')}\n`,
  );
}

async function buildSocketIoMsgpackParserAsset() {
  await esbuild.build({
    bundle: true,
    format: 'iife',
    logLevel: 'info',
    minify: !isWatch,
    outfile: join(vendorDir, 'socket.io-msgpack-parser', 'socket.io-msgpack-parser.js'),
    platform: 'browser',
    sourcemap: true,
    stdin: {
      contents: `
import * as parser from 'socket.io-msgpack-parser';
globalThis.SocketIoMsgpackParser = parser;
`,
      loader: 'js',
      resolveDir: process.cwd(),
      sourcefile: 'socketio-msgpack-parser.vendor.js',
    },
  });
}

async function prepareVendorAssets() {
  resetManagedVendorAssets();
  buildJetBrainsMonoCss();
  await buildSocketIoMsgpackParserAsset();
}

const codexAgent = {
  ...common,
  entryPoints: ['rust/crates/als-server/src/static/codex_agent.ts'],
  outfile: 'rust/crates/als-server/src/static/dist/codex_agent.js',
  format: 'esm',
};

await prepareVendorAssets();

if (isWatch) {
  const ctx = await esbuild.context(codexAgent);
  await ctx.watch();
  console.log('[build] watching…');
} else {
  await esbuild.build(codexAgent);
}
