import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import esbuild from 'esbuild';

const isWatch = process.argv.includes('--watch');
const staticDir = 'agent_log_server/static';
const distDir = join(staticDir, 'dist');
const vendorDir = join(staticDir, 'vendor');

mkdirSync(distDir, { recursive: true });

const common = {
  bundle: true,
  sourcemap: true,
  minify: !isWatch,
  logLevel: 'info',
  external: ['/static/vendor/*', 'https://*'],
};

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(dirname(dest));
  cpSync(src, dest);
}

function resetManagedVendorAssets() {
  const managedPaths = [
    join(vendorDir, 'fonts', 'jetbrains-mono'),
    join(vendorDir, 'fonts', 'jetbrains-mono.css'),
    join(vendorDir, 'highlight.js'),
    join(vendorDir, 'markdown-it'),
    join(vendorDir, 'socket.io-msgpack-parser'),
    join(vendorDir, 'streaming-markdown'),
    join(vendorDir, 'xterm'),
  ];
  for (const path of managedPaths) {
    rmSync(path, { recursive: true, force: true });
  }
}

function buildJetBrainsMonoCss() {
  const fontCssFiles = [
    '400.css',
    '400-italic.css',
    '500.css',
    '500-italic.css',
    '600.css',
    '600-italic.css',
    '700.css',
    '700-italic.css',
  ];
  const fontSourceRoot = 'node_modules/@fontsource/jetbrains-mono';
  const fontDestDir = join(vendorDir, 'fonts', 'jetbrains-mono');
  const fontFiles = new Set();
  const rewrittenBlocks = [];

  for (const cssFile of fontCssFiles) {
    const sourcePath = join(fontSourceRoot, cssFile);
    const sourceCss = readFileSync(sourcePath, 'utf8');
    for (const match of sourceCss.matchAll(/url\(\.\/files\/([^)]+?\.woff2)\)/g)) {
      fontFiles.add(match[1]);
    }
    const rewrittenCss = sourceCss.replace(
      /src:\s*url\(\.\/files\/([^)]+?\.woff2)\) format\('woff2'\),\s*url\(\.\/files\/[^)]+?\.woff\) format\('woff'\);/g,
      "src: url('./jetbrains-mono/$1') format('woff2');",
    );
    rewrittenBlocks.push(rewrittenCss.trim());
  }

  ensureDir(fontDestDir);
  for (const fontFile of fontFiles) {
    copyFile(join(fontSourceRoot, 'files', fontFile), join(fontDestDir, fontFile));
  }

  writeFileSync(
    join(vendorDir, 'fonts', 'jetbrains-mono.css'),
    `/* Generated by build.mjs from @fontsource/jetbrains-mono */\n\n${rewrittenBlocks.join('\n\n')}\n`,
  );
}

function copyStreamingMarkdownAsset() {
  copyFile('node_modules/streaming-markdown/smd.min.js', join(vendorDir, 'streaming-markdown', 'smd.min.js'));
}

function copyMarkdownItAsset() {
  copyFile('node_modules/markdown-it/dist/markdown-it.min.js', join(vendorDir, 'markdown-it', 'markdown-it.min.js'));
}

async function buildSocketIoMsgpackParserAsset() {
  await esbuild.build({
    bundle: true,
    format: 'iife',
    logLevel: 'info',
    minify: !isWatch,
    outfile: join(vendorDir, 'socket.io-msgpack-parser', 'socket.io-msgpack-parser.js'),
    platform: 'browser',
    sourcemap: true,
    stdin: {
      contents: `
import * as parser from 'socket.io-msgpack-parser';
globalThis.SocketIoMsgpackParser = parser;
`,
      loader: 'js',
      resolveDir: process.cwd(),
      sourcefile: 'socketio-msgpack-parser.vendor.js',
    },
  });
}

async function buildHighlightBundle() {
  copyFile(
    'node_modules/highlight.js/styles/github-dark.min.css',
    join(vendorDir, 'highlight.js', 'github-dark.min.css'),
  );

  await esbuild.build({
    bundle: true,
    format: 'iife',
    logLevel: 'info',
    minify: !isWatch,
    outfile: join(vendorDir, 'highlight.js', 'highlight.bundle.js'),
    platform: 'browser',
    sourcemap: true,
    stdin: {
      contents: `
import hljs from 'highlight.js/lib/core';
import python from 'highlight.js/lib/languages/python';
import bash from 'highlight.js/lib/languages/bash';
import javascript from 'highlight.js/lib/languages/javascript';
import typescript from 'highlight.js/lib/languages/typescript';
import rust from 'highlight.js/lib/languages/rust';
import go from 'highlight.js/lib/languages/go';
import json from 'highlight.js/lib/languages/json';
import kotlin from 'highlight.js/lib/languages/kotlin';
import css from 'highlight.js/lib/languages/css';
import scss from 'highlight.js/lib/languages/scss';
import markdown from 'highlight.js/lib/languages/markdown';
import xml from 'highlight.js/lib/languages/xml';
import ini from 'highlight.js/lib/languages/ini';
import yaml from 'highlight.js/lib/languages/yaml';
import sql from 'highlight.js/lib/languages/sql';
import dockerfile from 'highlight.js/lib/languages/dockerfile';

hljs.registerLanguage('python', python);
hljs.registerLanguage('bash', bash);
hljs.registerLanguage('javascript', javascript);
hljs.registerLanguage('typescript', typescript);
hljs.registerLanguage('rust', rust);
hljs.registerLanguage('go', go);
hljs.registerLanguage('json', json);
hljs.registerLanguage('kotlin', kotlin);
hljs.registerLanguage('css', css);
hljs.registerLanguage('scss', scss);
hljs.registerLanguage('markdown', markdown);
hljs.registerLanguage('xml', xml);
hljs.registerLanguage('ini', ini);
hljs.registerLanguage('yaml', yaml);
hljs.registerLanguage('sql', sql);
hljs.registerLanguage('dockerfile', dockerfile);

window.hljs = hljs;
`,
      loader: 'js',
      resolveDir: process.cwd(),
      sourcefile: 'highlight.vendor.js',
    },
  });
}

async function prepareVendorAssets() {
  resetManagedVendorAssets();
  buildJetBrainsMonoCss();
  copyStreamingMarkdownAsset();
  copyMarkdownItAsset();
  await buildSocketIoMsgpackParserAsset();
  await buildHighlightBundle();
}

const codexAgent = {
  ...common,
  entryPoints: ['agent_log_server/static/codex_agent.ts'],
  outfile: 'agent_log_server/static/dist/codex_agent.js',
  format: 'esm',
};

await prepareVendorAssets();

if (isWatch) {
  const ctx = await esbuild.context(codexAgent);
  await ctx.watch();
  console.log('[build] watching…');
} else {
  await esbuild.build(codexAgent);
}
