[package]
name = "als-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
ferrous-framework-pyo3 = ["ferrous_framework/pyo3-embed"]

[dependencies]
als-adapter-protocol.workspace = true
als-dto.workspace = true
als-jsonrpc.workspace = true
anyhow.workspace = true
axum.workspace = true
ferrous_framework.workspace = true
getrandom.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
socketioxide.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
