[package]
name = "als-server"
version = "0.2.123"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
als-adapter-protocol.workspace = true
als-dto.workspace = true
als-jsonrpc.workspace = true
anyhow.workspace = true
axum.workspace = true
flate2.workspace = true
ferrous_framework.workspace = true
futures-util.workspace = true
getrandom.workspace = true
git2.workspace = true
regex.workspace = true
rmp-serde.workspace = true
rust_socketio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
socketioxide.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
